[tool.poetry]
name = "django_polls"
version = "0.1.0"
description = "A basic poll application built with Django"
authors = ["Kevin Bowen <kevin.bowen@gmail.com>"]
license = "MIT License"

[tool.poetry.dependencies]
python = "^3.10"
Django = "^4.0.3"
environs = {extras = ["django"], version = "^9.5.0"}

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
